"""initial schema

Revision ID: 308e7f4e6cfd
Revises:
Create Date: 2026-05-27 12:01:50.561348

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "308e7f4e6cfd"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "leagues",
        sa.Column("league_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("platform", sa.String(), nullable=False),
        sa.Column("current_season_year", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("league_id"),
    )
    op.create_table(
        "pipeline_runs",
        sa.Column("run_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("mode", sa.String(length=32), nullable=True),
        sa.Column("sources_summary", sa.JSON(), nullable=True),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_table(
        "players",
        sa.Column("player_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name_full", sa.String(), nullable=False),
        sa.Column("name_first", sa.String(), nullable=True),
        sa.Column("name_last", sa.String(), nullable=True),
        sa.Column("position", sa.String(length=8), nullable=True),
        sa.Column("nfl_team", sa.String(length=8), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("rookie_year", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("nfl_com_player_id", sa.String(), nullable=True),
        sa.Column("gsis_id", sa.String(), nullable=True),
        sa.Column("sleeper_id", sa.String(), nullable=True),
        sa.Column("espn_id", sa.String(), nullable=True),
        sa.Column("yahoo_id", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("player_id"),
    )
    with op.batch_alter_table("players", schema=None) as batch_op:
        batch_op.create_index("ix_players_gsis_id", ["gsis_id"], unique=False)
        batch_op.create_index("ix_players_nfl_com_player_id", ["nfl_com_player_id"], unique=False)
        batch_op.create_index("ix_players_sleeper_id", ["sleeper_id"], unique=False)

    op.create_table(
        "owners",
        sa.Column("owner_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("league_id", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("nfl_user_id", sa.String(), nullable=True),
        sa.Column("aliases", sa.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("joined_year", sa.Integer(), nullable=True),
        sa.Column("left_year", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["league_id"], ["leagues.league_id"], name="fk_owners_league"),
        sa.PrimaryKeyConstraint("owner_id"),
    )
    op.create_table(
        "player_stats_raw",
        sa.Column("stat_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("season_year", sa.Integer(), nullable=False),
        sa.Column("week", sa.Integer(), nullable=False),
        sa.Column("season_type", sa.String(length=8), nullable=True),
        sa.Column("nfl_opponent", sa.String(length=8), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("stats", sa.JSON(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.player_id"], name="fk_player_stats_raw_player"
        ),
        sa.PrimaryKeyConstraint("stat_id"),
        sa.UniqueConstraint(
            "player_id",
            "season_year",
            "week",
            "source",
            name="uq_player_stats_raw_player_season_week_source",
        ),
    )
    with op.batch_alter_table("player_stats_raw", schema=None) as batch_op:
        batch_op.create_index(
            "ix_player_stats_raw_season_week", ["season_year", "week"], unique=False
        )

    op.create_table(
        "projections",
        sa.Column("projection_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("season_year", sa.Integer(), nullable=False),
        sa.Column("week", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("projected_stats", sa.JSON(), nullable=True),
        sa.Column("projected_points", sa.Float(), nullable=True),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["player_id"], ["players.player_id"], name="fk_projections_player"),
        sa.PrimaryKeyConstraint("projection_id"),
        sa.UniqueConstraint(
            "player_id",
            "season_year",
            "week",
            "source",
            "fetched_at",
            name="uq_projections_player_season_week_source_fetched",
        ),
    )
    with op.batch_alter_table("projections", schema=None) as batch_op:
        batch_op.create_index("ix_projections_season_week", ["season_year", "week"], unique=False)

    op.create_table(
        "seasons",
        sa.Column("season_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("league_id", sa.String(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("regular_season_weeks", sa.Integer(), nullable=True),
        sa.Column("playoff_weeks", sa.Integer(), nullable=True),
        sa.Column("champion_team_id", sa.Integer(), nullable=True),
        sa.Column("runner_up_team_id", sa.Integer(), nullable=True),
        sa.Column("last_place_team_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["champion_team_id"], ["teams.team_id"], name="fk_seasons_champion", use_alter=True
        ),
        sa.ForeignKeyConstraint(
            ["last_place_team_id"], ["teams.team_id"], name="fk_seasons_last_place", use_alter=True
        ),
        sa.ForeignKeyConstraint(["league_id"], ["leagues.league_id"], name="fk_seasons_league"),
        sa.ForeignKeyConstraint(
            ["runner_up_team_id"], ["teams.team_id"], name="fk_seasons_runner_up", use_alter=True
        ),
        sa.PrimaryKeyConstraint("season_id"),
        sa.UniqueConstraint("league_id", "year", name="uq_seasons_league_year"),
    )
    op.create_table(
        "source_health",
        sa.Column("health_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("rows_added", sa.Integer(), nullable=True),
        sa.Column("rows_updated", sa.Integer(), nullable=True),
        sa.Column("parse_failures", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["run_id"], ["pipeline_runs.run_id"], name="fk_source_health_run"),
        sa.PrimaryKeyConstraint("health_id"),
    )
    op.create_table(
        "player_stats_scored",
        sa.Column("scored_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("stat_id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("week", sa.Integer(), nullable=False),
        sa.Column("total_points", sa.Float(), nullable=True),
        sa.Column("points_breakdown", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.player_id"], name="fk_player_stats_scored_player"
        ),
        sa.ForeignKeyConstraint(
            ["season_id"], ["seasons.season_id"], name="fk_player_stats_scored_season"
        ),
        sa.ForeignKeyConstraint(
            ["stat_id"], ["player_stats_raw.stat_id"], name="fk_player_stats_scored_stat"
        ),
        sa.PrimaryKeyConstraint("scored_id"),
        sa.UniqueConstraint("stat_id", "season_id", name="uq_player_stats_scored_stat_season"),
    )
    op.create_table(
        "scoring_rules",
        sa.Column("rule_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("stat_key", sa.String(), nullable=False),
        sa.Column("points_per_unit", sa.Float(), nullable=True),
        sa.Column("unit_size", sa.Float(), nullable=True),
        sa.Column("threshold_min", sa.Float(), nullable=True),
        sa.Column("threshold_max", sa.Float(), nullable=True),
        sa.Column("flat_points", sa.Float(), nullable=True),
        sa.Column("raw_text", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["season_id"], ["seasons.season_id"], name="fk_scoring_rules_season"
        ),
        sa.PrimaryKeyConstraint("rule_id"),
        sa.UniqueConstraint(
            "season_id",
            "category",
            "stat_key",
            "threshold_min",
            name="uq_scoring_rules_season_cat_key_thresh",
        ),
    )
    op.create_table(
        "teams",
        sa.Column("team_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("team_name", sa.String(), nullable=True),
        sa.Column("team_abbrev", sa.String(length=8), nullable=True),
        sa.Column("draft_position", sa.Integer(), nullable=True),
        sa.Column("final_rank", sa.Integer(), nullable=True),
        sa.Column("regular_season_wins", sa.Integer(), nullable=True),
        sa.Column("regular_season_losses", sa.Integer(), nullable=True),
        sa.Column("regular_season_ties", sa.Integer(), nullable=True),
        sa.Column("regular_season_points_for", sa.Float(), nullable=True),
        sa.Column("regular_season_points_against", sa.Float(), nullable=True),
        sa.Column("made_playoffs", sa.Boolean(), nullable=True),
        sa.Column("playoff_finish", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["owners.owner_id"], name="fk_teams_owner"),
        sa.ForeignKeyConstraint(["season_id"], ["seasons.season_id"], name="fk_teams_season"),
        sa.PrimaryKeyConstraint("team_id"),
        sa.UniqueConstraint("season_id", "owner_id", name="uq_teams_season_owner"),
        sa.UniqueConstraint("season_id", "team_name", name="uq_teams_season_team_name"),
    )
    op.create_table(
        "matchups",
        sa.Column("matchup_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("week", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("opponent_team_id", sa.Integer(), nullable=True),
        sa.Column("team_score", sa.Float(), nullable=True),
        sa.Column("opponent_score", sa.Float(), nullable=True),
        sa.Column("is_win", sa.Boolean(), nullable=True),
        sa.Column("is_playoff", sa.Boolean(), nullable=False),
        sa.Column("is_consolation", sa.Boolean(), nullable=False),
        sa.Column("nfl_com_game_id", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["opponent_team_id"], ["teams.team_id"], name="fk_matchups_opponent"
        ),
        sa.ForeignKeyConstraint(["season_id"], ["seasons.season_id"], name="fk_matchups_season"),
        sa.ForeignKeyConstraint(["team_id"], ["teams.team_id"], name="fk_matchups_team"),
        sa.PrimaryKeyConstraint("matchup_id"),
        sa.UniqueConstraint("season_id", "week", "team_id", name="uq_matchups_season_week_team"),
    )
    op.create_table(
        "player_availability",
        sa.Column("availability_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("season_year", sa.Integer(), nullable=False),
        sa.Column("week", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("owning_team_id", sa.Integer(), nullable=True),
        sa.Column("waiver_claim_deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_status_change", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_pre_kickoff_snapshot", sa.Boolean(), nullable=False),
        sa.Column("extra_data", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owning_team_id"], ["teams.team_id"], name="fk_player_availability_team"
        ),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.player_id"], name="fk_player_availability_player"
        ),
        sa.PrimaryKeyConstraint("availability_id"),
        sa.UniqueConstraint(
            "player_id",
            "season_year",
            "week",
            "is_pre_kickoff_snapshot",
            name="uq_player_availability_player_season_week_kickoff",
        ),
    )
    with op.batch_alter_table("player_availability", schema=None) as batch_op:
        batch_op.create_index(
            "ix_player_availability_season_week_status",
            ["season_year", "week", "status"],
            unique=False,
        )
        batch_op.create_index(
            "ix_player_availability_team_week", ["owning_team_id", "week"], unique=False
        )

    op.create_table(
        "team_rosters",
        sa.Column("roster_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("season_year", sa.Integer(), nullable=False),
        sa.Column("week", sa.Integer(), nullable=False),
        sa.Column("roster_slot", sa.String(length=16), nullable=True),
        sa.Column("is_starter", sa.Boolean(), nullable=True),
        sa.Column("was_locked_at_kickoff", sa.Boolean(), nullable=True),
        sa.Column("acquisition_type", sa.String(length=32), nullable=True),
        sa.Column("acquisition_week", sa.Integer(), nullable=True),
        sa.Column("acquisition_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("drop_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("extra_data", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.player_id"], name="fk_team_rosters_player"
        ),
        sa.ForeignKeyConstraint(["team_id"], ["teams.team_id"], name="fk_team_rosters_team"),
        sa.PrimaryKeyConstraint("roster_id"),
        sa.UniqueConstraint(
            "team_id", "player_id", "week", name="uq_team_rosters_team_player_week"
        ),
    )
    with op.batch_alter_table("team_rosters", schema=None) as batch_op:
        batch_op.create_index(
            "ix_team_rosters_player_acquisition", ["player_id", "acquisition_date"], unique=False
        )
        batch_op.create_index(
            "ix_team_rosters_player_season", ["player_id", "season_year"], unique=False
        )
        batch_op.create_index("ix_team_rosters_team_week", ["team_id", "week"], unique=False)

    op.create_table(
        "transactions",
        sa.Column("transaction_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("transaction_type", sa.String(length=32), nullable=False),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("effective_week", sa.Integer(), nullable=True),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("counterpart_team_id", sa.Integer(), nullable=True),
        sa.Column("player_id", sa.Integer(), nullable=True),
        sa.Column("direction", sa.String(length=8), nullable=True),
        sa.Column("waiver_priority_used", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["counterpart_team_id"], ["teams.team_id"], name="fk_transactions_counterpart"
        ),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.player_id"], name="fk_transactions_player"
        ),
        sa.ForeignKeyConstraint(
            ["season_id"], ["seasons.season_id"], name="fk_transactions_season"
        ),
        sa.ForeignKeyConstraint(["team_id"], ["teams.team_id"], name="fk_transactions_team"),
        sa.PrimaryKeyConstraint("transaction_id"),
    )
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_transactions_season_player", ["season_id", "player_id"], unique=False
        )
        batch_op.create_index("ix_transactions_season_team", ["season_id", "team_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_index("ix_transactions_season_team")
        batch_op.drop_index("ix_transactions_season_player")

    op.drop_table("transactions")
    with op.batch_alter_table("team_rosters", schema=None) as batch_op:
        batch_op.drop_index("ix_team_rosters_team_week")
        batch_op.drop_index("ix_team_rosters_player_season")
        batch_op.drop_index("ix_team_rosters_player_acquisition")

    op.drop_table("team_rosters")
    with op.batch_alter_table("player_availability", schema=None) as batch_op:
        batch_op.drop_index("ix_player_availability_team_week")
        batch_op.drop_index("ix_player_availability_season_week_status")

    op.drop_table("player_availability")
    op.drop_table("matchups")
    op.drop_table("teams")
    op.drop_table("scoring_rules")
    op.drop_table("player_stats_scored")
    op.drop_table("source_health")
    op.drop_table("seasons")
    with op.batch_alter_table("projections", schema=None) as batch_op:
        batch_op.drop_index("ix_projections_season_week")

    op.drop_table("projections")
    with op.batch_alter_table("player_stats_raw", schema=None) as batch_op:
        batch_op.drop_index("ix_player_stats_raw_season_week")

    op.drop_table("player_stats_raw")
    op.drop_table("owners")
    with op.batch_alter_table("players", schema=None) as batch_op:
        batch_op.drop_index("ix_players_sleeper_id")
        batch_op.drop_index("ix_players_nfl_com_player_id")
        batch_op.drop_index("ix_players_gsis_id")

    op.drop_table("players")
    op.drop_table("pipeline_runs")
    op.drop_table("leagues")
    # ### end Alembic commands ###
