"""add_player_injury_reports

Revision ID: 407521092d7e
Revises: c1a4f7e2d8b3
Create Date: 2026-06-11 13:46:49.807537

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "407521092d7e"
down_revision: str | Sequence[str] | None = "c1a4f7e2d8b3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player_injury_reports",
        sa.Column("report_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("season_year", sa.Integer(), nullable=False),
        sa.Column("week", sa.Integer(), nullable=False),
        sa.Column("game_type", sa.String(length=8), nullable=True),
        sa.Column("report_status", sa.String(length=32), nullable=True),
        sa.Column("report_primary_injury", sa.String(length=64), nullable=True),
        sa.Column("report_secondary_injury", sa.String(length=64), nullable=True),
        sa.Column("practice_status", sa.String(length=128), nullable=True),
        sa.Column("date_modified", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.player_id"], name="fk_player_injury_reports_player"
        ),
        sa.PrimaryKeyConstraint("report_id"),
        sa.UniqueConstraint(
            "player_id",
            "season_year",
            "week",
            "game_type",
            name="uq_player_injury_report_player_season_week_gametype",
        ),
    )
    with op.batch_alter_table("player_injury_reports", schema=None) as batch_op:
        batch_op.create_index(
            "ix_player_injury_report_season_week", ["season_year", "week"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("player_injury_reports", schema=None) as batch_op:
        batch_op.drop_index("ix_player_injury_report_season_week")

    op.drop_table("player_injury_reports")
    # ### end Alembic commands ###
